version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: php_apache_8_3
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    environment:
      - XDEBUG_MODE=develop,debug
      - XDEBUG_CONFIG="client_host=host.docker.invalid"
    depends_on:
      - mariadb
    networks:
      - app-network

  mariadb:
    build:
      context: .
      dockerfile: docker/mariadb/Dockerfile
    container_name: mariadb_11
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: slimdb
      MYSQL_USER: slim
      MYSQL_PASSWORD: slim123
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci", "--max-connections=1000", "--max_allowed_packet=128M"]
    healthcheck:
      test: ["CMD-SHELL", "/usr/local/bin/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: root
      UPLOAD_LIMIT: 128M
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  composer:
    image: composer:latest
    container_name: composer
    user: "${UID}:${GID}"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - COMPOSER_HOME=/app/.composer
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
  redis_data:
